### ISSUE TITLE
criterion.yml syntax

### ISSUE THREAD

**Issue by marcqualie** [romhut/criterion#12]
I'm really not a fan of "test" as the keyspace for running things in the file. "script" like what travis has makes much more sense. I think you got "test" from phpci, which is a bad name. CI is more than just testing, it's integration so you may be running build scripts, compilation or even setting up keys etc.

Also, "pass" and "fail" should be optional. Looks messy having them in there but empty.

**Comment by scottrobertson** [comment]
Yeah i agree, ill get it changed to "script".

And they are optional, i just have them there just now to show that they can be used.

**Comment by marcqualie** [comment]
Ah okay, I just noticed them set as empty on the romhut api repo, thought they were needed. My bad.

**Comment by scottrobertson** [comment]
Naa it's my bad. I just quickly copied that over from here, and they are empty here until we can get some docs written up.
