### ISSUE TITLE
Internal system data is displayed

### ISSUE THREAD

**Issue by marcqualie** [romhut/criterion#14]
When running tests I get this in the web ui.

```
$ rm -rf /tests/51e17c684c3e4c5cf48ba5cd/51e17cf44c3e4c5cf4286add
There is no output for this command.
```

I think this should be hidden because it's no use in the UI. Is there a way to mark certain commands as "internal" that aren't part of the tests themselves?

**Comment by scottrobertson** [comment]
I was in 2 minds about this, id kinda like them to see all output, but i am inclined to agree. I did strip out the DATA_DIR so they can not see full paths etc.

**Comment by marcqualie** [comment]
Yeah being able to see all output is a good thing, but my argument is simply that this is internal to Criterion's functionality, and not the test itself so it should be hidden. It's kind of like a cleanup command.

Using DATA_DIR was a really neat idea, looks much cleaner now in the output.

**Comment by scottrobertson** [comment]
I have added that, and added the 2 "rm" for fail and pass commands as internal only. I am trying to think of how to cleanup the clone command, looks a bit shit. I have an idea.
