### ISSUE TITLE
Code Path Review

### ISSUE THREAD

**Issue by marcqualie** [romhut/criterion#17]
I'm not sure if we should be using /src for the code. That's normally reserved for libraries along with /lib. Standalone applications tend to use /app. This would be pretty easy to change within composer.json as wouldn't affect any code (unless you've put in absolute paths to things).

Also, since there is only ever one config file would it be better to have that config.json file in the root of the repo? I don't think we need a whole directory for configs since we don't do different environments right now and probably won't ever need to due to the nature of the app.

**Comment by scottrobertson** [comment]
Changing to /app will be easy yeah. The only thing that would break is the twig view path in index.php

And yeah i was thinking that with config files. I shall get them changes in the feature/installer branch.

**Comment by scottrobertson** [comment]
Config file has been moved.
