### ISSUE TITLE
Convert helpers to none static

### ISSUE THREAD

**Issue by scottrobertson** [romhut/criterion#23]
Convert the helpers to none static so we can use __construct to set \Criterion\Application()

**Comment by marcqualie** [comment]
Why would this be needed? The helpers shouldn't need to access the application. If they do, they should access the static method on \Criterion\Application directly, not from itself.

**Comment by scottrobertson** [comment]
Ahh right, that is what i am doing now, but i thought it would be a bit messy.

**Comment by marcqualie** [comment]
It's a lot less messy and better on memory footprint/code maintainability to have one central static method to get the application instance.

**Comment by scottrobertson** [comment]
Yeah :) well that's already done so closing.
