### ISSUE TITLE
Poller interval not clearing when complete

### ISSUE THREAD

**Issue by scottrobertson** [romhut/criterion#26]
The poller interval is not clearing when `data.status.code == '1' or '0'`

**Comment by outrunthewolf** [comment]
I'll have a look tonight

**Comment by outrunthewolf** [comment]
Can't test the system, can't log in to it without commenting all the auth stuff out.

Fresh build, username and password don't seem to grant me any access, when I force a user I have no admin access. Here's a shot of my DB:
![crit_mongo_issue](https://f.cloud.github.com/assets/814246/807331/8acdd508-ee4c-11e2-90e8-40736b9d8cf4.png)

Is that not a little empty? Anyway advise when you have a minute, or create a new ticket if its a real issue

**Comment by scottrobertson** [comment]
Yeah that's a bit odd. I shall have a look in a bit. Just on my way home.

**Comment by scottrobertson** [comment]
_id is meant to be the username. It will be an issue with the models.

**Comment by marcqualie** [comment]
You and your shitty models. Bet you didn't even unit test any of them!

**Comment by scottrobertson** [comment]
Not yet no :P i didnt mean to put it into master if i am totally honest.

**Comment by scottrobertson** [comment]
If you switch to feature/none-basic-auth you should be able to do everything. Make sure you drop the users collection as data structure has changed a little. See: https://github.com/romhut/criterion/pull/29

**Comment by outrunthewolf** [comment]
nice thanks
