### ISSUE TITLE
Concatenate/Minify JS/CSS

### ISSUE THREAD

**Issue by scottrobertson** [romhut/criterion#28]
Should we bother doing this? Since its not going to be running at a large scale just yet it may not be an issue. @marcqualie @outrunthewolf

**Comment by marcqualie** [comment]
Na I don't think this is needed. Maybe add it in the future but there's other stuff that's higher priority.

**Comment by outrunthewolf** [comment]
Plus you might end up in a situation where your forever changing and re-minfying over and over un-till things are 100%

**Comment by marcqualie** [comment]
We'd need environments, and minification would be a pre-deploy hook to production. Something more complex than is currently supported by this codebase.

**Comment by scottrobertson** [comment]
Yeah I agree. Closing for now.
