### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by marcqualie** [romhut/criterion#33]
The UI should have network hooks after the tests have failed or passed. In this screen there could also be options like notifications (send email when failed) and where to send them.

The simplest hook could be "when passed hit the url". The url would then do whatever it needs, similar to how git hooks work when commits are pushed.

A more complex iteration could be "push to remote". If the tests pass, push this commit onto another remote automatically. A lot of people already use git based deployment so this would be ideal.

**Comment by marcqualie** [comment]
Ws should tie into other services such as deployhq and heroku for easier deployments. Either by using API or pushing directly to a git repository on completion.

**Comment by scottrobertson** [comment]
Yeah that would be good. I think allowing git push would be the best bet, then we can just use the same SSH keys for the project.
