### ISSUE TITLE
Web Installer

### ISSUE THREAD

**Issue by marcqualie** [romhut/criterion#35]
The issue we're having with the installer could be solved by having a simple web installer. Prompting for input during an automated install process is bad practice and will cause a lot of issues, stopping it being scripted which is bad for what I want to extend onto.

I've thought up a new process. The install process simple builds the system and it's dependencies, making it workable. The configuration then comes later. It's down the user to either run

```
bin/configure --db=mongo://127.0.0.1 --url=http://criterion.example.com
```

or go to the web interface and configure through there. Each option they do not pass to the cli tool they will be prompted for. If people want to fully automate the install they can simply build their own script which uses our installer then calls configure with all of their options set.

**Comment by scottrobertson** [comment]
I think a web installer would be good. The only thing that is stopping us doing it in command line automatically is the need for a URL for things like Github Statuses API etc.

**Comment by marcqualie** [comment]
I mentioned how we get around that in the code example above.

**Comment by scottrobertson** [comment]
Well yeah, but if you are running it with custom params you might as well just use the installer we have now.

**Comment by marcqualie** [comment]
Install and configure are two different options. Installation means all of the dependencies are ready and the system can function properly. Configuration comes after when you want to tune it specifically to your system. Whether you do it at the same time or afterwards it's still two stages.

You may also want to reconfigure variables afterwards, so having a separate tool for that would make sense. You wouldn't be re-installing it, just changing variables such as the url or email settings. The web ui would also interact with it at the core level, passing the same options. Could probably even make a configuration model.

**Comment by scottrobertson** [comment]
Yeah i get what you mean. It's just annoying that we need the URL and that there is no way of detecting it.
