### ISSUE TITLE
Status Image Text

### ISSUE THREAD

**Issue by marcqualie** [romhut/criterion#36]
The status image should really say "passing" instead of "passed". Makes more sense for a status and that's how all over CI tools display it.

**Comment by scottrobertson** [comment]
:+1: 

Although i do think they could do with being properly designed. That was me spending like 3 minutes in Photoshop :P

**Comment by marcqualie** [comment]
Yeah. Personally I think they shoudl match the same style as all of the other open source images so that it can fit in with people's READMEs. People are then more likely to adopt it and spread awareness.

Here is an example of two different projects displaying their images in the same style: https://github.com/php-loep/statsd. There is also a lot of ruby ci tools and coverage tools that have the same style. Criterion should just have it's own colour theme for branding that would match criterion web interface.

**Comment by scottrobertson** [comment]
When i did the images i was going to make it very similar, but i wasn't sure if that would just be seen as copying. I know they are open source, but you know what i mean.

**Comment by outrunthewolf** [comment]
Shame there's no standard here, to offer a universal badge with a small area set aside for branding. I think this guy is on the right lines:

https://github.com/olivierlacan/shields/tree/api

But still has a way to go

**Comment by scottrobertson** [comment]
Yeah they seem quite cool. Anyone any good with Photoshop? :P
