### ISSUE TITLE
Multiple PHP Versions

### ISSUE THREAD

**Issue by marcqualie** [romhut/criterion#37]
When adding environmental variables (#32) we should add the option to run mutiple php versions. Criterion should be responsible for installing these php binaries onto the machine by downloading their source code and compiling.

Then inside .criterion.yml we can allow them to do version: 5.4 etc like travis does. This is especially useful for testing libraries and making sure you don't accidentally add 5.5 only features when coding and testing against your own builds of php.

**Comment by scottrobertson** [comment]
Yeah that could work. Are we going to mainly support PHP with this for now? And then add support for other things at a later date?
