### ISSUE TITLE
Discussion: PHP Only?

### ISSUE THREAD

**Issue by scottrobertson** [romhut/criterion#39]
I have been thinking about this for a while now. The way Criterion is built, it will allow any tests to be run from any language, but should we mainly build for PHP? 

I know this will probably be a controversial question amongst people, but it's just a question at this stage. 

By "mainly build for PHP" i mean that so most of our features work awesomely with PHP and integrate in nicely. Such as #38

**Comment by marcqualie** [comment]
Yeah I agree with full PHP integration. We can add really cool language specific stuff that way.

**Comment by scottrobertson** [comment]
It does make sense with it being written in PHP too. If someone wishes to add support for other language specific features down the line, it should be easy enough.
