### ISSUE TITLE
Test Status Image

### ISSUE THREAD

**Issue by scottrobertson** [romhut/criterion#4]
Add test status images. This can be as simple as redirecting to /test/image/123 to pass.jpg or fail.jpg. Or it can be more complex if we want it to be.

**Comment by scottrobertson** [comment]
These are added in but need designed properly.

**Comment by marcqualie** [comment]
The best way to do this would be generate the files as they are requested on a per branch basis, then flush them every time a build on that branch/commit happens. I can build this in tonight if you like?

I can also design the logos (I have full legal adobe suite) to match the standards of all of the other test systems such as travis?

**Comment by scottrobertson** [comment]
Yeah that would be totally fine. 

The images can just be flat images and just either redirect to them, or load them and display them. I cant really see a need to generate them, unless you want to put the branch name on them.

**Comment by scottrobertson** [comment]
Now that auth is fully in, we need a way to get around it on status images. This could be quite easy, for example just having an array of urls that are allowed, or we could make a bit better.

**Comment by marcqualie** [comment]
We should mimic http://about.travis-ci.org/docs/user/status-images/ so that people can just flip out the domain to display criterion images.

As for authentication the urls end in .png. We could simply make all "static" urls bypass authentication since they will be rendering content regardless of auth.

**Comment by scottrobertson** [comment]
The only issue with that is that we support more than just Github. I think just putting project ID would be fine for now. I know its not as clean but it will allow for better long term support.

**Comment by marcqualie** [comment]
Putting the project ID would look horrible. We could easily match up the url. What are the odds of someone having the same vendor/package name on their own install of criterion across two different git providers.

**Comment by scottrobertson** [comment]
I guess yeah. Well we store `{short_repo: "romhut/criterion"}` in the projects collection, so it should be easy enough.

**Comment by marcqualie** [comment]
If it ever does become an issue, where people have the same repo on multiple providers for some odd reason then we could add ?origin=github to the url or something same as how branch is done. We should really group them together within the UI anyways, the the origin set based on the git provider. But as I said, we should only add this functionality if it's requested or we get bored one day when open sourced.

**Comment by scottrobertson** [comment]
We do store the provider as well, so that should be easy. Are you going to do this or should i?

**Comment by marcqualie** [comment]
These need to have headers set so the response doesn't get cached. Currently they're being cached by Github's CND, fastly which defeats the point. They should be called directly from the server each time, with no http caching.
