### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by scottrobertson** [romhut/criterion#5]
Add an installer to the console:
- Check dependencies
- Create first user account
- Generate config.json
  - Url
  - Email
- chmod +x bin/git
- Offer to add "hook" user
- Offer to add sample projects (Criterion, MongoMinify, Hoard)

**Comment by marcqualie** [comment]
How is progress on this going? It should be as simple as possible, and the web UI should aware if the system hasn't been configured yet. You could even make it configurable through the webui?

**Comment by scottrobertson** [comment]
Not started this yet, not added Auth yet so didn't want to touch this yet.

**Comment by scottrobertson** [comment]
Auth wont be added for now, i think we can safely rely on http auth.

Note that `src/bin/git.sh` needs to be made executable by the installer.

**Comment by marcqualie** [comment]
If you're going to rely on HTTP Basic Auth you should have a way to create/manage users from the cli. Want me to add this in?

**Comment by scottrobertson** [comment]
Yeah you could do. Or would it be easy to just build an actual auth system?

**Comment by marcqualie** [comment]
A simple auth system would be just as easy. You could even has http basic auth at the application level instead of the web server level to keep it self contained.

**Comment by scottrobertson** [comment]
Yeah that would be good. It then means we don't need to build a token system for the hooks either, we can just keep using http basic auth.

**Comment by scottrobertson** [comment]
#13 Auth System

**Comment by scottrobertson** [comment]
I have updated the first comment with potential contents of installer
