### ISSUE TITLE
Server Side Configuration

### ISSUE THREAD

**Issue by marcqualie** [romhut/criterion#58]
There have been multiple requests for server side configuration which will override any settings inside criterion.yml. This will help when you need to run subsets of commands or different tests/checks to what is available within the project repository.

I suggest this configuration be in the same format, a yml editior in the web interface which will then be decoded and stored in the database with the project as "config" key and json data.

**Comment by scottrobertson** [comment]
What would be the advantage of storing it as json? Can we not just store it normally in Mongo so we can read individual items back if needed?

**Comment by scottrobertson** [comment]
Also, this could tie in nicely with #33

**Comment by marcqualie** [comment]
Mongo is json (well, bson).. so it would be stored in MongoDB's native format. If I was going to store it as flat text I would have just kept it in yml format to save to conversion.

**Comment by scottrobertson** [comment]
My bad. It was just because you explicitly said JSON it sounded like you meant flat text.

**Comment by scottrobertson** [comment]
Added in #64
