### ISSUE TITLE
Detect environment if no criterion.yml is found

### ISSUE THREAD

**Issue by marcqualie** [romhut/criterion#6]
The builds shouldn't simply fail if no criterion.yml file does not exist. Insyead it should fail gracefully and try to "figure out" the system. 90% of the time, you won't need to include a file in the repo.

By default all php system's should run "phpunit" as the only command and this will work. If a composer.json exists in the repo root simply run "composer install" before running "phpunit". Will save a lot of hassle adding files everywhere as most repos wont' need a lot of the extra functionality, and if they do.. simply add the file to overwrite the defaults.

**Comment by scottrobertson** [comment]
That is a really cool idea. Should not be too hard to add in either.

**Comment by marcqualie** [comment]
Yeah you've already got a check in for the file. I know for a fact every single one of my repos would work straight off with the above defaults and no files needed to be added. Extremely useful for open source stuff.

**Comment by scottrobertson** [comment]
So i have added phpunit detection, and its alot easier to add new ones now.
