### ISSUE TITLE
Support for driver-based Database Engine

### ISSUE THREAD

**Issue by toopay** [romhut/criterion#61]
First of all, nice job with this project.

However, i would love to see if this project could also support different database engines (RiakDB, Couch or even SQL-based engine?). We could use something like Doctrine perhaps?

Abstracting away the model from hardcoded Mongo-specific syntax and support driver-based db will immenselly helpful for others that want to have this app but already depend on other db engine than Mongo.

Thanks.

**Comment by scottrobertson** [comment]
Hello,

Thank you for your kind words, really means a lot.

I fully agree with supporting other DB engines, and that is partly why we used models so we could do it in the future. Although i do I think there are still a few places with Mongo queries, such as the worker.

Technically it should not be too hard to switch it out and allow multiple engines. Once things are a little more stable and we are fully happy i think its something we will do. I can't really see a reason why we could not just support most DB engines such as MySQL and RiakDB. 

Thanks
Scott
