### ISSUE TITLE
Local Folders

### ISSUE THREAD

**Issue by scottrobertson** [romhut/criterion#67]
Add the ability to use local repos:
- [x] Check that it's a local folder in Repo::cloneCommand()
- [x] Issue "cp" command in Repo::cloneCommand()
- [x] Run usual process from then on (excluding clone)

**Comment by scottrobertson** [comment]
I think the best way to do this would be to check if `$project->repo` is a directory when issuing the clone command. This would reduce the need for parsing the string out etc.

**Comment by marcqualie** [comment]
We could do a repo "source" when you create it? If it's git, put the git repo in, or a path to a directory if it's local type.

**Comment by scottrobertson** [comment]
Yeah that is what i was planning on doing. I shall just rename the label to "Source (GIt or Directory)". No point renaming the mongo field.
