### ISSUE TITLE
Override Branch

### ISSUE THREAD

**Issue by scottrobertson** [romhut/criterion#77]
Allow the branch to be picked in project config settings. It will use this one unless a test is specifically passed in (from hooks).

**Comment by marcqualie** [comment]
The branch should be on a per-test basis. When you click "run-test" it should have a drop down arrow next to it listing all of the branches on the project to select from, or option to type in your own if it can't detect branches.

**Comment by scottrobertson** [comment]
Yeah that sounds good. Could you write a helper method in Helper\Repo to generate an array of branches, should be easy enough.

**Comment by scottrobertson** [comment]
Found that this can be done by passing ?branch=BLAH at the end of the start test url. Just needs a UI around it now. @outrunthewolf?
